/*
 * Organization Management API
 * API for managing organizations, departments, teams, and user assignments.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SurveyManagementApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SurveyManagementApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SurveyManagementApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for organizationsIdOrganizationAssignSurveySurveyIdPost
     * @param idOrganization  (required)
     * @param surveyId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Survey assigned successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organizationsIdOrganizationAssignSurveySurveyIdPostCall(@javax.annotation.Nonnull Integer idOrganization, @javax.annotation.Nonnull Integer surveyId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organizations/{idOrganization}/assign-survey/{surveyId}"
            .replace("{" + "idOrganization" + "}", localVarApiClient.escapeString(idOrganization.toString()))
            .replace("{" + "surveyId" + "}", localVarApiClient.escapeString(surveyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call organizationsIdOrganizationAssignSurveySurveyIdPostValidateBeforeCall(@javax.annotation.Nonnull Integer idOrganization, @javax.annotation.Nonnull Integer surveyId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idOrganization' is set
        if (idOrganization == null) {
            throw new ApiException("Missing the required parameter 'idOrganization' when calling organizationsIdOrganizationAssignSurveySurveyIdPost(Async)");
        }

        // verify the required parameter 'surveyId' is set
        if (surveyId == null) {
            throw new ApiException("Missing the required parameter 'surveyId' when calling organizationsIdOrganizationAssignSurveySurveyIdPost(Async)");
        }

        return organizationsIdOrganizationAssignSurveySurveyIdPostCall(idOrganization, surveyId, _callback);

    }

    /**
     * Assign a survey to a department or team
     * 
     * @param idOrganization  (required)
     * @param surveyId  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Survey assigned successfully </td><td>  -  </td></tr>
     </table>
     */
    public void organizationsIdOrganizationAssignSurveySurveyIdPost(@javax.annotation.Nonnull Integer idOrganization, @javax.annotation.Nonnull Integer surveyId) throws ApiException {
        organizationsIdOrganizationAssignSurveySurveyIdPostWithHttpInfo(idOrganization, surveyId);
    }

    /**
     * Assign a survey to a department or team
     * 
     * @param idOrganization  (required)
     * @param surveyId  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Survey assigned successfully </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> organizationsIdOrganizationAssignSurveySurveyIdPostWithHttpInfo(@javax.annotation.Nonnull Integer idOrganization, @javax.annotation.Nonnull Integer surveyId) throws ApiException {
        okhttp3.Call localVarCall = organizationsIdOrganizationAssignSurveySurveyIdPostValidateBeforeCall(idOrganization, surveyId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Assign a survey to a department or team (asynchronously)
     * 
     * @param idOrganization  (required)
     * @param surveyId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Survey assigned successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organizationsIdOrganizationAssignSurveySurveyIdPostAsync(@javax.annotation.Nonnull Integer idOrganization, @javax.annotation.Nonnull Integer surveyId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = organizationsIdOrganizationAssignSurveySurveyIdPostValidateBeforeCall(idOrganization, surveyId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
