/*
 * Organization Management API
 * API for managing organizations, departments, teams, and user assignments.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Department;
import org.openapitools.client.model.DepartmentCreate;
import org.openapitools.client.model.DepartmentUpdate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DepartmentManagementApi
 */
@Disabled
public class DepartmentManagementApiTest {

    private final DepartmentManagementApi api = new DepartmentManagementApi();

    /**
     * Get all departments
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void departmentsGetTest() throws ApiException {
        List<Department> response = api.departmentsGet();
        // TODO: test validations
    }

    /**
     * Delete a department
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void departmentsIdDepartmentDeleteTest() throws ApiException {
        Integer idDepartment = null;
        api.departmentsIdDepartmentDelete(idDepartment);
        // TODO: test validations
    }

    /**
     * Get department details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void departmentsIdDepartmentGetTest() throws ApiException {
        Integer idDepartment = null;
        Department response = api.departmentsIdDepartmentGet(idDepartment);
        // TODO: test validations
    }

    /**
     * Update a department
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void departmentsIdDepartmentPutTest() throws ApiException {
        Integer idDepartment = null;
        DepartmentUpdate departmentUpdate = null;
        api.departmentsIdDepartmentPut(idDepartment, departmentUpdate);
        // TODO: test validations
    }

    /**
     * Create a department
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void departmentsPostTest() throws ApiException {
        DepartmentCreate departmentCreate = null;
        Department response = api.departmentsPost(departmentCreate);
        // TODO: test validations
    }

}
