/*
 * Organization Management API
 * API for managing organizations, departments, teams, and user assignments.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Organization;
import org.openapitools.client.model.OrganizationCreate;
import org.openapitools.client.model.OrganizationUpdate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganizationManagementApi
 */
@Disabled
public class OrganizationManagementApiTest {

    private final OrganizationManagementApi api = new OrganizationManagementApi();

    /**
     * Get all organizations
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void organizationsGetTest() throws ApiException {
        List<Organization> response = api.organizationsGet();
        // TODO: test validations
    }

    /**
     * Get child departments or teams of an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void organizationsIdOrganizationChildrenGetTest() throws ApiException {
        Integer idOrganization = null;
        List<Organization> response = api.organizationsIdOrganizationChildrenGet(idOrganization);
        // TODO: test validations
    }

    /**
     * Delete an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void organizationsIdOrganizationDeleteTest() throws ApiException {
        Integer idOrganization = null;
        api.organizationsIdOrganizationDelete(idOrganization);
        // TODO: test validations
    }

    /**
     * Get details of an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void organizationsIdOrganizationGetTest() throws ApiException {
        Integer idOrganization = null;
        Organization response = api.organizationsIdOrganizationGet(idOrganization);
        // TODO: test validations
    }

    /**
     * Update an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void organizationsIdOrganizationPutTest() throws ApiException {
        Integer idOrganization = null;
        OrganizationUpdate organizationUpdate = null;
        api.organizationsIdOrganizationPut(idOrganization, organizationUpdate);
        // TODO: test validations
    }

    /**
     * Create a new organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void organizationsPostTest() throws ApiException {
        OrganizationCreate organizationCreate = null;
        Organization response = api.organizationsPost(organizationCreate);
        // TODO: test validations
    }

    /**
     * Search organizations by name or type
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void organizationsSearchGetTest() throws ApiException {
        String name = null;
        String type = null;
        List<Organization> response = api.organizationsSearchGet(name, type);
        // TODO: test validations
    }

}
